#! /usr/bin/python
from weshappening import db, Event, Location, delete_event, add_event
from subprocess import call
import logging

logging.basicConfig(filename="weshappening.log", level=logging.DEBUG,
                        format="%(asctime)s: %(message)s")
logging.debug("Cleaning database")

for ev in Event.query.all():
    delete_event(ev.name)

call(["./feed"])

logging.debug("Database clean!")
